import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';

import './globals.css';

import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pl'>
      <body className={`${spaceGrotesk.variable} antialiased`}>
        <div className='bg-void flex h-screen w-full overflow-hidden'>
          <Sidebar />

          {/* Main Content */}
          <main className='relative flex min-w-0 flex-1 flex-col overflow-hidden'>
            {/* Background Grid */}
            <div className='bg-grid-pattern pointer-events-none absolute inset-0 bg-size-[40px_40px] opacity-10' />

            {/* Top Bar */}
            <Header />

            <div className='flex-1 overflow-auto p-4 md:p-6 lg:p-8'>{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
